# vim: ft=yaml.ansible
---
- name: Add Prometheus Community Helm repository
  kubernetes.core.helm_repository:
    state: present
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Install Kube Prometheus Stack
  kubernetes.core.helm:
    state: present
    name: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values:
      # helm show values prometheus-community/kube-prometheus-stack | bat -l yaml
      alertmanager:
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            kubernetes.io/ingress.class: 'traefik'
            cert-manager.io/cluster-issuer: 'letsencrypt'
          hosts:
            - 'alertmanager.{{ domain }}'
          paths:
            - /
          pathType: Prefix
          tls:
            - secretName: alertmanager-ingress-cert
              hosts:
                - 'alertmanager.{{ domain }}'

      grafana:
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            kubernetes.io/ingress.class: 'traefik'
            cert-manager.io/cluster-issuer: 'letsencrypt'
          hosts:
            - 'grafana.{{ domain }}'
          paths:
            - /
          pathType: Prefix
          tls:
            - secretName: grafana-ingress-cert
              hosts:
                - 'grafana.{{ domain }}'

    kubeconfig: ../outputs/kubeconfig.yaml
