---
- name: Add Prometheus Community Helm repository
  kubernetes.core.helm_repository:
    state: present
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Install Kube Prometheus Stack
  kubernetes.core.helm:
    state: present
    name: prometheus-community
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    kubeconfig: ../outputs/kubeconfig.yaml
