# vim: ft=yaml.ansible
---
- name: Add Longhorn Helm repository
  kubernetes.core.helm_repository:
    state: present
    name: longhorn
    repo_url: https://charts.longhorn.io
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Install Longhorn
  kubernetes.core.helm:
    state: present
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    values:
      defaultSettings:
        defaultDataPath: '/storage01'
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Apply Longhorn Ingress
  kubernetes.core.k8s:
    state: present
    template: longhorn-ingress.yml
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Make Longhorn storage class the default
  kubernetes.core.k8s:
    state: patched
    kind: StorageClass
    name: local-path
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: 'false'
    kubeconfig: ../outputs/kubeconfig.yaml
