---
- name: Add cert-manager Helm repository
  kubernetes.core.helm_repository:
    state: present
    name: jetstack
    repo_url: https://charts.jetstack.io
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Install cert-manager
  kubernetes.core.helm:
    state: present
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      installCRDs: 'true'
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Apply DigitalOcean DNS Secret
  kubernetes.core.k8s:
    state: present
    template: digitalocean-dns-secret.yaml.j2
    kubeconfig: ../outputs/kubeconfig.yaml
  vars:
    access_token: "{{ lookup('community.general.onepassword', 'DigitalOcean K3s API Token', field='token', vault='Private') }}"

- name: Apply LetsEncrypt Issuer
  kubernetes.core.k8s:
    state: present
    template: letsencrypt-issuer.yaml.j2
    kubeconfig: ../outputs/kubeconfig.yaml
  vars:
    email: "{{ lookup('community.general.onepassword', 'K3s LetsEncrypt Issuer', field='email', vault='Private') }}"
