# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless
type: Opaque
data:
  PAPERLESS_SECRET_KEY: {{ .Values.PAPERLESS_SECRET_KEY | b64enc }}
  PAPERLESS_ADMIN_USER: {{ .Values.PAPERLESS_ADMIN_USER | b64enc }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.PAPERLESS_ADMIN_PASSWORD | b64enc }}
