---
- hosts: cluster

  tasks:
    - name: Get master ip address
      shell: |
        ip addr show eth0 | grep 'inet ' | awk '{ print $2 }' | cut -f1 -d'/'
      register: master_ip
      when: "'master' in group_names"

    - name: Fetch kubeconfig file from master node
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../outputs/kubeconfig.yaml
        flat: true
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      become: true

    - name: Replace master node IP in Kubeconfig
      ansible.builtin.lineinfile:
        path: ../outputs/kubeconfig.yaml
        search_string: 'server: https://127.0.0.1:6443'
        line: '    server: https://{{ master_ip.stdout }}:6443'
        mode: '0644'
      run_once: true
      delegate_to: localhost
