# vim: ft=yaml.ansible
---
- name: Get KUBECONFIG from master node
  hosts: cluster

  tasks:
    - name: Get master ip address
      ansible.builtin.shell: |
        set -o pipefail
        ip addr show eth0 | grep 'inet ' | awk '{ print $2 }' | cut -f1 -d'/'
      args:
        executable: /bin/bash
      changed_when: false
      register: master_ip
      when: "'master' in group_names"

    - name: Fetch kubeconfig file from master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../outputs/kubeconfig.yaml
        flat: true
      delegate_to: "{{ groups['master'][0] }}"
      become: true

    - name: Replace master node IP in Kubeconfig
      ansible.builtin.lineinfile:
        path: ../outputs/kubeconfig.yaml
        search_string: 'server: https://127.0.0.1:6443'
        line: '    server: https://{{ master_ip.stdout }}:6443'
        mode: '0644'
      # noqa: run-once[task]
      run_once: true
      delegate_to: localhost
