# vim: ft=yaml.ansible
---
- name: Bootstrap
  hosts: localhost
  tasks:
    - name: Install Helm Diff plugin
      kubernetes.core.helm_plugin:
        state: present
        plugin_path: https://github.com/databus23/helm-diff

- name: Install cert-manager
  hosts: localhost
  tags: [cert-manager]
  roles:
    - role: cert_manager

- name: Configure Traefik
  hosts: localhost
  tags: [traefik]
  roles:
    - role: traefik

- name: Install Longhorn
  hosts: localhost
  tags: [longhorn]
  roles:
    - role: longhorn

- name: Install ArgoCD
  hosts: localhost
  tags: [argocd]
  roles:
    - role: argocd

- name: Install External Secrets
  hosts: localhost
  tags: [external-secrets]
  roles:
    - role: external_secrets
