# vim: ft=yaml.ansible
---
- name: Add CloudNativePG Helm repository
  tags:
    - cnpg
  kubernetes.core.helm_repository:
    state: present
    name: cnpg
    repo_url: https://cloudnative-pg.github.io/charts
    kubeconfig: ../outputs/kubeconfig.yaml

- name: Install CloudNativePG (cnpg)
  tags:
    - cnpg
  kubernetes.core.helm:
    state: present
    name: cnpg
    chart_ref: cnpg/cloudnative-pg
    release_namespace: cnpg-system
    create_namespace: true
    kubeconfig: ../outputs/kubeconfig.yaml
