---
- name: Update apt repository
  apt:
    update_cache: true
  become: true

- name: Upgrade packages
  apt:
    upgrade: true
  become: true

- name: Install packages
  apt:
    pkg:
      - bat
      - lsscsi
      - neovim
      - nfs-common
      - open-iscsi
      - sg3-utils
      - util-linux
  become: true
